// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9PeRbs6XhngKi7tJSx24v9DBKGQ_kZjY',
    appId: '1:193559220082:web:36f3ce780b9cd2863417eb',
    messagingSenderId: '193559220082',
    projectId: 'doctor-f3fb9',
    authDomain: 'doctor-f3fb9.firebaseapp.com',
    storageBucket: 'doctor-f3fb9.firebasestorage.app',
    measurementId: 'G-16035JGCXS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBt85oztuZGdeY2Bbr7E_uaDL1K4qid1c',
    appId: '1:193559220082:android:84a0229fa61be05f3417eb',
    messagingSenderId: '193559220082',
    projectId: 'doctor-f3fb9',
    storageBucket: 'doctor-f3fb9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVLIOyYVYD9lfGKQ0pMGcJEsHYQe-9UHg',
    appId: '1:193559220082:ios:51795087667728293417eb',
    messagingSenderId: '193559220082',
    projectId: 'doctor-f3fb9',
    storageBucket: 'doctor-f3fb9.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVLIOyYVYD9lfGKQ0pMGcJEsHYQe-9UHg',
    appId: '1:193559220082:ios:51795087667728293417eb',
    messagingSenderId: '193559220082',
    projectId: 'doctor-f3fb9',
    storageBucket: 'doctor-f3fb9.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9PeRbs6XhngKi7tJSx24v9DBKGQ_kZjY',
    appId: '1:193559220082:web:c7f50462bb07a3773417eb',
    messagingSenderId: '193559220082',
    projectId: 'doctor-f3fb9',
    authDomain: 'doctor-f3fb9.firebaseapp.com',
    storageBucket: 'doctor-f3fb9.firebasestorage.app',
    measurementId: 'G-CH03KN9208',
  );

}